version: '3.8'

services:
  db:
    image: postgres:15.4
    container_name: postgres_15_4
    restart: unless-stopped
    environment:
      POSTGRES_USER: helmi
      POSTGRES_PASSWORD: agustian
      POSTGRES_DB: helmidb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
