version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - ${ELASTICSEARCH_REST_PORT}:9200
      - ${ELASTICSEARCH_NODE_PORT}:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - es7net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    environment:
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
      - elasticsearch.hosts=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - es7net

  cerebro:
    image: lmenezes/cerebro:0.9.4
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
    networks:
      - es7net

volumes:
    elastic:
      driver: local

networks:
  es7net:
    driver: bridge
